src/cardi/urls.py
from django.contrib import admin
from django.urls import path
from patient.views import (create_patient,
                            patient_detail, 
                            patient_report, 
                            all_patients, 
                            search, 
                            # create_medicine, 
                            delete_patient,
                            add_disease,
                            index,
                            )

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('patient/create/', create_patient, name='patient-create'),
    # path('patient/detail/<id>', patient_detail, name='patient-detail'),
    path('patient/report/<id>', patient_report, name='patient-report'),
    path('patient/all/', all_patients, name='all-patients'),
    path('patient/search/', search, name='search'),
    # path('medicine/create/', create_medicine, name='create-medicine'),
    path('patient/delete/<id>', delete_patient, name='delete-patient'),
    path('patient/detail/<id>', add_disease, name="patient-detail")
]

src/patient/models.py
from django.db import models

genders = {
    ('M','Male'),
    ('F','Female'),
}

medicine_quantity = {
    ('1','One Time'),
    ('2','Two Time'),
    ('3','Three Time'),
}

class Patient(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    gender = models.CharField(choices=genders,max_length=1)
    # phone_number = models.IntegerField()
    address = models.CharField(max_length=300, blank=True, null=True)
    disease = models.ManyToManyField("Disease", blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    #prescription = models.ManyToManyField("MedicineIntake", blank=True)


    def __str__(self):
        return self.name



class Disease(models.Model):
    name = models.CharField(max_length=50)


    def __str__(self):
        return self.name
    

class Medicine(models.Model):
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name


class MedicineIntake(models.Model):
    # medicine = models.CharField(max_length=100, blank=True, null=True)
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE, null=True, blank=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, null=True, blank=True)
    disease = models.ForeignKey(Disease, on_delete=models.CASCADE, null=True, blank=True)
    dose = models.CharField(max_length=20)
    quantity = models.CharField(choices=medicine_quantity, max_length=5)
    duration = models.IntegerField()


    def __str__(self):
        # return str(self.medicine.name) + " - " + str(self.medicine.company)  + " - " + self.quantity   + " times a day - " + self.dose  + " - " + str(self.duration) + " days."
        return self.medicine

'''
class Prescription(models.Model):
    medicine = models.ManyToManyField(MedicineIntake)
    time_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
'''

src/templates/abstract_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shafiq Clinic</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/ff00e4a8c7.js" crossorigin="anonymous"></script>
</head>

<body>
    {% block navbar %}
    {% endblock %}

    <div class="container">
        
        
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
</body>
</html>

src/templates/base.html
{% extends 'abstract_base.html' %}
    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock navbar %}
        
        
    {% block content %}
    {% endblock content %}

src/templates/create_medicine.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-6">
        <h3>Add Medicine</h3>
        <hr/>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="mt-3 btn btn-primary" type="submit">Add Medicine</button>
        </form>
    </div>
    <div class="col-6">
        <h3>Medicines List</h3>
        <hr/>
        {% for med in medicines %}
            <div class="card m-3">
              <div class="card-body">
                <h1 class="display-6" style="font-size:25px;">
                    <span class="badge bg-primary">
                  {{med.id}}
                </span>
                  {{med.name}}
                </h1>
              </div>
            </div>
          {% empty %}
          <div class="card">
              <div class="card-body">
                  You have no medicines
              </div>
            </div>
          {% endfor %}
    </div>
</div>


{% endblock %}

src/templates/create_patient.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-6">
        <h1 class="mt-3">Add a new patient</h1>
        <form method="POST">
            {% csrf_token %}
            {{patient_form|crispy}}
            <button class="btn btn-primary m-3" type="submit" name="add_patient">Add Patient</button>
        </form>
        
    </div>
    <div class="col-6">
        <h1 class="mt-3 ml-3">
            Patients List
        </h1>

            {% for patient in final %}
            <a href="{% url 'patient-detail' patient.id %}">
              <div class="card m-3">
                <div class="card-body">
                  <h1 class="display-6" style="font-size:25px;">
                      <span class="badge bg-primary">
                    {{patient.id}}
                  </span>
                    {{patient.name}}
                  </h1>
                </div>
              </div>
            </a>
            {% empty %}
            <div class="card">
                <div class="card-body">
                    You have no patients
                </div>
              </div>
            {% endfor %}
            {% if patients %}
            <a class="btn btn-primary btn-block m-3 mr-5" href="{% url 'all-patients' %}">View all patients</a>
            {% endif %}
    </div>
</div>
{% endblock content %}

src/templates/disease.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block content%}
<style>

</style>
<div class="row">
  <h1 class="display-4 mb-3" style="margin:0; text-align:center;">
<span style="font-size:x-large">ID: {{patient.id}}</span>
{{patient.name}}
      <a class="btn btn-primary" style="text-align:right; width:150px; " href="{% url 'patient-report' patient.id %}">Generate Report</a></h1>
  <br/>
  <div class="col-7">
      <div class="card p-4">
        <h2>General Information</h2>
        <h4 class="display-6" style="margin:0; font-size:25px;">Age: {{patient.age}} years</h4>
        <h4 class="display-6" style="margin:0; font-size:25px;">Phone Number: {{patient.phone_number}}</h4>
        <h4 class="display-6" style="margin:0; font-size:25px;">Gender: {{patient.get_gender_display }}</h4>
        <br/>
        <h2>Diseases</h2>
        {% for disease in diseases %}
        <form method="POST">
            {% csrf_token %}
            <div class="card p-3 mt-3 bg-light">
                <h4>
                    {{disease.name}}
                </h4>
                <input type="hidden" name='disease' value="{{disease.id}}">
        
                <button class="btn btn-primary" type="submit" name='diseasebutton'>Add Disease</button>
            </div>
            
        </form>
    
        {% empty %}
        <p>No Disease Detected</p>
        {% endfor %}
      </div>
  </div>
  <div class="col-5">
      <div class="card p-4">
        <h2>Prescription</h2>
        <form method="POST">{% csrf_token %}
          {{ formset.management_form }}
          {% for form in formset %}
          <tr><td><ul class="card p-3 bg-light">{{ form|crispy }}</ul></td></tr>
          {% endfor %}
            <button class="btn btn-primary btn-lg mt-3 btn-block" type="submit" name="medicineintake">Save</button>
        </form>
      </div>
  </div>
</div>
    


{%endblock content%}

src/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-4 col-md-6">
        <a href="/admin" style="text-decoration: none;" class="text-white">
            <div class="card p-3 bg-danger">
                <div class="card-body text-center">
                    <h1>Admin Page</h1>
                </div>
            </div>
        </a>
    </div>
    <div class="col-lg-4 col-md-6">
        <a href="{% url 'patient-create' %}" style="text-decoration: none;" class="text-white">
            <div class="card p-3 bg-success">
                <div class="card-body text-center">
                    <h1>Add Patient</h1>
                </div>
            </div>
        </a>
    </div>
    <div class="col-lg-4 col-md-6">
        <a href="{% url 'all-patients' %}" style="text-decoration: none;" class="text-white">
            <div class="card p-3 bg-primary">
                <div class="card-body text-center">
                    <h1>Patients List</h1>
                </div>
            </div>
        </a>
    </div>
    </div>
</div>
{% endblock content %}

patient-create
patient-report
all-patients
create-medicine
patient-detail

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="/" style="font-size: 30px;">Shafiq Clinic</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link"
            aria-current="page"
            href="{% url 'patient-create' %}"
            >Add a patient</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link "
            aria-current="page"
            href="{% url 'all-patients' %}"
            >Patients List</a
          >
        </li>
      </ul>
      <form class="d-flex m-3 text-right" style="width:500px;" method="GET" action="{% url 'search' %}">
        <input class="form-control mr-2" type="number" placeholder="Search for a patient by id" aria-label="Search" name="search" >
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

src/templates/patient_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{%block content%}
<div class="row">
    <h1 class="display-4" style="margin:0; text-align:center;">
  <span style="font-size:x-large">ID: {{patient.id}}</span>
  {{patient.name}}
        <a class="btn btn-primary" style="text-align:right; width:150px;" href="{% url 'patient-report' patient.id %}">Generate Report</a></h1>
    <br/>
    <hr/>
    <div class="col-6">
        <h4 class="display-6" style="margin:0; font-size:25px;">Age: {{patient.age}} years</h4>
        <h4 class="display-6" style="margin:0; font-size:25px;">Phone Number: {{patient.phone_number}}</h4>
        <h4 class="display-6" style="margin:0; font-size:25px;">Gender: {{patient.get_gender_display }}</h4>
        
        <h4 class="display-6 mt-3" style="margin:0; font-size:25px;">Current Prescription:</h4>
        {% for prescription in patient.prescription.all %}
        <div class="card mt-2">
            <div class="card-body">
              <h1 class="display-6" style="font-size:25px;">
                {{prescription}}
                <form method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="id" value={{prescription.id}} />
                  <input class="btn btn-primary mt-2" type="submit" value="Delete" name="delete"/>
              </form>
              </h1>
            </div>
          </div>
        {%empty%}
        <p>Patient does not have any known prescription</p>
        {% endfor %}
    </div>
    <div class="col-6">
        <h4>Prescribe Medicine to this patient</h4>
        <hr/>
      <form method="POST">
          {% csrf_token %}
          {{form|crispy}}
          <button type="submit" class="btn btn-primary mt-2">Prescribe</button>
      </form>
    </div>
      
</div>
    

{%endblock content%}

src/templates/patient_report.html
{% extends 'abstract_base.html' %}

{% block content %}
<div class="mt-3" style="width:700px; border: 1px solid black; text-align:center;">
    <h1 class="m-3" style="margin:0;">Shafiq Clinic</h1>
    <h2 style="font-weight:100; margin:0;">Patient Report</h2>
    <div class="row mt-3">
        <div class="col-8">
            <div class="card p-1 mt-3 ml-3">
                <div class="card-body">
                    Patient Name: 
                    <h1 class="display-6" style="font-size:32px;">
                        {{patient.name}}
                    </h1>
                    <p>
                        Record Created: {{patient.created|date}}
                    </p>
                    <p>
                    </p>
                    
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card p-1 mt-3 mr-3">
                <div class="card-body">
                    <p>
                        id # {{patient.id}}<br>
                        Age: {{patient.age}}<br>
                        Phone Number: {{patient.phone_number}}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card m-3">
                <div class="card-header">
                    Prescription:
                </div>
                <div class="card-body">
                    
                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Medicine Name</th>
                            <th scope="col">Dose</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Duration (in days)</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for meds in patient.medicineintake_set.all %}
                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{meds.medicine}}</td>
                            <td>{{meds.dose}}</td>
                            <td>{{meds.quantity}}</td>
                            <td>{{meds.duration}}</td>
                          </tr>
                          {% empty %}
                          <p>Medicine not prescribed</p><br>
                          {% endfor %}
                        </tbody>
                      </table>
                    <p>Back to <a href="{% url 'patient-detail' patient.id %}">Patient Detail Page</a></p>
                    </div>
            </div>
        </div>
    </div>
</div>
<br>
<script>
    print()
</script>
{% endblock content %}

src/templates/patients_list.html
{% extends 'base.html' %}

{% block content %}
<div style="width:500px;" >
    
    {% for patient in patients %}
    <a href="{% url 'patient-detail' patient.id %}">
      <div class="card m-3">
        <div class="card-body">
          <h1 class="display-6" style="font-size:25px; text-align:center; margin:0; line-height: 0;">
              <span class="badge bg-primary">
            {{patient.id}}
          </span>
            {{patient.name}}
          </h1>
             </a>
             <a type="button" data-toggle="modal" data-target="#patient-{{patient.id}}">
                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
              </a>
        </div>
      </div>
      <!-- Modal -->
      <div class="modal fade" id="patient-{{patient.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Are you sure you want to delete?<br>
              Patient id:
              <span class="badge bg-danger">
                {{patient.id}}
              </span>
              {{patient.name}} 
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <a type="button" class="btn btn-danger" href="{% url 'delete-patient' patient.id %}">Yes, delete</a>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
    <div class="card">
        <div class="card-body">
            You have no patients
        </div>
      </div>
    {% endfor %}
</div>

{% endblock content %}

src/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'patient-detail' patient.id %}">
      <div class="card m-3">
        <div class="card-body">
          <h1 class="display-6" style="font-size:25px;">
              <span class="badge bg-primary">
            {{patient.id}}
          </span>
            {{patient.name}}
          </h1>
        </div>
      </div>
    </a>

{% endblock content %}